### PR TITLE
Change exception message to include given input parameter value

### PR DESCRIPTION
**Pull request by SandGrainOne**
## Description
This might make it every so slightly easier to analyze invalid authorization requests.

### CODE REVIEW

**Comment by Alxandr** [comment]
Maybe also change it to an ArgumentException at the same time?

**Comment by SandGrainOne** [comment]
> Maybe also change it to an ArgumentException at the same time?

I can change it. I didn't at first because I wasn't sure if it would be right. The method is private and it's checking a value on something deep into a data structure. What would the argument be?

**Comment by Alxandr** [comment]
The argument is still the `attributes` collection. It contains something invalid. There are other alternative exception types that could be used (InvalidOperationException is the typical "I couldn't think of anything better" exception type). It's generally not a good idea to throw a base `Exception`. SonarCloud also complains about it. Alternatively, you could make your own exception type. `UnsupportedXacmlDataTypeException`? You could then easily enrich it with the information you want for debugging as well.

**Comment by Alxandr** [comment]
Also note that these are just suggestions. My opinions on the matter is still non-autoreactive :)

**Review by TheTechArch — APPROVED** [review]
I think this works

**Pull request merged**
